### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by adharna** [zahiid/KingTouch#9]
`[Adharna11]Server request connecting ...
[Adharna11]{"assetsUrl":"https://ankama.akamaized.net/games/dofus-tablette/assets/2.15.17","analytics":{"ankAnalytics":{"version":"1","debug":false,"analog":false,"useUrlMap":true},"wizAnalytics":{"localytics":{"token":"9f0bf865fd57d22f0bbea56-cd08f12a-8138-11e5-7c24-00736b041834","options":{"sessionTimeoutSeconds":60,"namespace":"dofus-production"}}}},"disabledFeatures":{},"adjust":{"appToken":"7j60imkfu60w","environment":"EnvironmentProduction"},"logging":{"groups":false,"logLevels":{"time":0,"verbose":0,"debug":1,"info":2,"notice":3,"warning":4,"error":5,"critical":6,"alert":7,"emergency":8},"config":{"console":["none"],"server":["error","critical","alert","emergency"]},"disableOverride":false},"dataUrl":"https://proxyconnection.touch.dofus.com","proxyUrl":"https://proxyconnection.touch.dofus.com","haapi":{"id":18,"url":"https://haapi.ankama.com/json/Ankama/v2"},"serverLanguages":["en","de","es","fr","it","pt"],"failoverLanguage":"en","uiUrl":"https://proxyconnection.touch.dofus.com/assets","language":"en","sessionId":"BgF6akchksy79x84"}
[Adharna11]Config loaded !
[Adharna11]{"key":"7314a59a-1a58-4ee6-828d-fed005ab1f22","account_id":119078921,"ip":"124.169.123.121","added_date":"2017-08-18T03:51:17+02:00","meta":[],"data":{"country":"AU","currency":"AUD"},"access":[],"refresh_token":"93de5b5b-8d67-4819-972d-4787da18f9ad","expiration_date":"2017-08-18T06:51:17+02:00"}
[Adharna11]Api key : 7314a59a-1a58-4ee6-828d-fed005ab1f22
[Adharna11]Game token : 631588fc9de53bfc51d7a77400f26cc5
[Adharna11][Aucun groupe:0:info][processIdentification]...
[Adharna11]Connecting to login server (https://proxyconnection.touch.dofus.com?STICKER=BgF6akchksy79x84) ...
[Adharna11]Connection opened !
[Adharna11][Aucun groupe:0:info]Identification connection opened !
[Adharna11]Prmus close connection !
[Adharna11][Aucun groupe:0:info]<span color="red">Connection closed, reloading client ...</span>
[Adharna11]Session for Adharna11 exported !
Trace: { reason: 'reconnecting' }
    at ChildProcess.process.on (c:\Users\Mickael\Dropbox\Tools\Bot\KingTouch-master\KingToutchManager\processFrame.js:12:17)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
********** Child process handle error, reloading (Adharna11) ! **********
********** Process frame request for reloading ... ***********
*********** trying to rescure client ... **********`

Franchement c'est du tres beau boulot, ta une idee du pourquoi sa bug ?

**Comment by adharna** [comment]
'Message reveived :'
{ _messageType: 'ConnectionFailedMessage',
  reason: 'INCOMPATIBLEAPPVERSIONS' }

**Comment by adharna** [comment]
129:4{"call":"connecting","data":{"language":"fr","server":"login","client":"android","appVersion":"1.10.0","buildVersion":"1.14.0"}}
